name: Docker Image CI CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3   

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: sravankolla/my-demo-actions-app:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove existing Container and Image and run latest image from docker hub
        uses: actions/checkout@v3  
      - run : docker stop demopythonapp 2> /dev/null || true 
      - run : docker rm demopythonapp 2> /dev/null || true 
      - run : docker rmi sravankolla/my-demo-actions-app 2> /dev/null || true
      - run : docker run -itd --name demopythonapp -p 5050:5000 --restart unless-stopped  sravankolla/my-demo-actions-app
